package com.example.testgreendao.entity;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.testgreendao.bean.StudentBook;

import com.example.testgreendao.bean.BookB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "db_book_b".
*/
public class BookBDao extends AbstractDao<BookB, Long> {

    public static final String TABLENAME = "db_book_b";

    /**
     * Properties of entity BookB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BookName = new Property(1, String.class, "bookName", false, "book_name");
    }

    private DaoSession daoSession;

    private Query<BookB> studentB_BookBListQuery;

    public BookBDao(DaoConfig config) {
        super(config);
    }
    
    public BookBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"db_book_b\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"book_name\" TEXT);"); // 1: bookName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"db_book_b\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(2, bookName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(2, bookName);
        }
    }

    @Override
    protected final void attachEntity(BookB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BookB readEntity(Cursor cursor, int offset) {
        BookB entity = new BookB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // bookName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bookBList" to-many relationship of StudentB. */
    public List<BookB> _queryStudentB_BookBList(Long studentId) {
        synchronized (this) {
            if (studentB_BookBListQuery == null) {
                QueryBuilder<BookB> queryBuilder = queryBuilder();
                queryBuilder.join(StudentBook.class, StudentBookDao.Properties.BookId)
                    .where(StudentBookDao.Properties.StudentId.eq(studentId));
                studentB_BookBListQuery = queryBuilder.build();
            }
        }
        Query<BookB> query = studentB_BookBListQuery.forCurrentThread();
        query.setParameter(0, studentId);
        return query.list();
    }

}
